volumes:
      rabbitmq_data:
      sqlserver_data:
        
networks:
      main:
        driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - main
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
  
  azure-sql-edge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azure-sql-edge
    environment:
      MSSQL_SA_PASSWORD: Str#ng_Passw#rd
      ACCEPT_EULA: Y
    ports:
      - "1434:1433"
    networks:
      - main
    volumes:
      - sqlserver_data:/var/lib/azsql/data
      
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
  
  gateway:
    image: thulomaepaa/bas-gateway:latest
    container_name: gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "4201:80"
    networks:
      - main
    depends_on:
      - azure-sql-edge
      - rabbitmq
      - redis
  
  account-management-service:
    image: thulomaepaa/bas-account-management-service:latest
    container_name: account-management-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "4202:80"
    networks:
      - main
    depends_on:
      - azure-sql-edge
      - rabbitmq
      - redis
      - gateway