services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # networks:
    #   - spring
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
  
  azure-sql-edge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azure-sql-edge-container
    environment:
      SA_PASSWORD: MyStrong@Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
      
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

volumes:
      rabbitmq_data: